# Configuration de build
[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# Configuration des fonctions
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]
  timeout = 30

# Redirections
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 