# Configuration globale
[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

# Configuration de développement
[dev]
  command = "npm run start"
  port = 8888
  targetPort = 3000
  publish = "build"
  autoLaunch = true

# Configuration des fonctions
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]
  timeout = 30
  included_files = ["netlify/functions/**/*"]

# Redirections
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval';"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains" 